version: '3'

services:
  nginx:
    image: nginx:1.19.2-alpine
    container_name: studio_nginx
    volumes:
      - ./laravel:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${NGINX_EXPOSED_PORT:-0}:80
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - php

  php:
    build: ./docker/php/fpm
    image: studio_php
    container_name: studio_php
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./laravel:/app
      - ~/.ssh:/root/.ssh
    ports:
      - ${PHP_EXPOSED_PORT:-0}:9000
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:5.0-alpine3.8
    container_name: studio_redis
    restart: unless-stopped
    ports:
      - ${REDIS_EXPOSED_PORT:-0}:6379

  mysql:
    image: mysql:5.7.31
    container_name: studio_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    ports:
      - ${DB_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

  supervisor:
    build: ./docker/supervisor
    container_name: studio_supervisor
    restart: always
    working_dir: /app
    volumes:
      - ./laravel:/app
      - "./docker/supervisor/config/supervisord.conf:/etc/supervisor/supervisord.conf"
      - "./docker/supervisor/config/laravel-worker.conf:/etc/supervisor/conf.d/app.conf"
    command: [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]
    depends_on:
      - php

  #  cron:
  #    build: ./docker/php/cli
  #    container_name: studio_cron
  #    restart: always
  #    working_dir: /app
  #    command: [ "/usr/sbin/crond", "-f", "-d", "0" ]
  #    volumes:
  #      - ./laravel:/app
  #    depends_on:
  #      - php

  node:
    build: ./docker/node
    container_name: studio_node
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - ${NODE_EXPOSED_PORT:-0}:3000
